workflows:
  android-workflow:
    name: Build Android APK (Java 11)
    max_build_duration: 30
    environment:
      flutter: stable
      java: 11
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --debug --no-shrink
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
