workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    environment:
      flutter: stable   # veya belirli sürüm: 3.19.6
      java: 11
    scripts:
      - name: Get dependencies
        script: flutter pub get

      - name: Build debug APK
        script: flutter build apk --debug

    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk

    publishing:
      email:
        recipients:
          - your@email.com
